const menu = [
	{
		id: 1,
		title: "buttermilk pancakes",
		category: "breakfast",
		price: 15.99,
		img: "/images/item-1.jpeg",
		desc: `Fluffy, golden-brown buttermilk pancakes stacked high and drizzled with warm maple syrup. Served with a side of fresh berries and a dusting of powdered sugar.`,
	},
	{
		id: 2,
		title: "diner double",
		category: "lunch",
		price: 13.99,
		img: "/images/item-2.jpeg",
		desc: `A classic double cheeseburger with two juicy beef patties, melted American cheese, bacon, crisp lettuce, tomato, pickles, and our signature house sauce on a toasted bun.`,
	},
	{
		id: 3,
		title: "godzilla milkshake",
		category: "shakes",
		price: 6.99,
		img: "/images/item-3.jpeg",
		desc: `A monstrous strawberry milkshake loaded with whipped cream, chocolate drizzle, crushed cookies, donuts, and fresh fruit on top. Big enough to satisfy any sweet tooth!`,
	},
	{
		id: 4,
		title: "country delight",
		category: "breakfast",
		price: 20.99,
		img: "/images/item-4.jpeg",
		desc: `A hearty country-style breakfast featuring fluffy eggs, crispy bacon, homemade biscuits with sausage gravy, and golden hash browns.`,
	},
	{
		id: 5,
		title: "egg attack",
		category: "lunch",
		price: 22.99,
		img: "/images/item-5.jpeg",
		desc: `A towering cheeseburger topped with a perfectly fried egg, crispy bacon, and melted cheddar cheese, all on a toasted brioche bun. Served with seasoned fries.`,
	},
	{
		id: 6,
		title: "oreo dream",
		category: "shakes",
		price: 18.99,
		img: "/images/item-6.jpeg",
		desc: `A rich and creamy cookies-and-cream milkshake blended with real Oreo cookies, topped with whipped cream, chocolate drizzle, and extra cookie crumbles.`,
	},
	{
		id: 7,
		title: "bacon overflow",
		category: "breakfast",
		price: 8.99,
		img: "/images/item-7.jpeg",
		desc: `A warm, buttery biscuit sandwich stuffed with crispy bacon, a fluffy scrambled egg, and melted cheddar cheese. Served with a side of hash browns.`,
	},
	{
		id: 8,
		title: "american classic",
		category: "lunch",
		price: 12.99,
		img: "/images/item-8.jpeg",
		desc: `An all-American meal featuring a grilled cheeseburger, crispy fries, and a side of coleslaw. Simple, satisfying, and timeless.`,
	},
	{
		id: 9,
		title: "quarantine buddy",
		category: "shakes",
		price: 16.99,
		img: "/images/item-9.jpeg",
		desc: `A giant vanilla milkshake made for two—but ironically enjoyed solo. Topped with whipped cream and two straws, just in case you decide to share.`,
	},
];

export default menu;
